[workspace]
channels = ["conda-forge", "nvidia"]
name = "DeCoF"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
cuda-toolkit = ">=12.9,<12.10"
cudnn = ">=9,<10"
pixi-pycharm = ">=0.0.9,<0.0.10"

[pypi-dependencies]
tqdm = ">=4.67.1, <5"
einops = ">=0.8.1, <0.9"
numpy = ">=2.2.6, <3"
scikit-learn = ">=1.7.2, <2"
pillow = ">=12.0.0, <13"
ftfy = ">=6.3.1, <7"
regex = ">=2025.10.23, <2026"
opencv-python-headless = ">=4.12.0.88, <5"
scipy = ">=1.15.3, <2"
torch = { version = ">=2.9.0, <2.10", index = "https://download.pytorch.org/whl/cu129" }
torchvision = { version = ">=0.24.0, <0.25", index = "https://download.pytorch.org/whl/cu129" }
